### ISSUE TITLE
Allow print(supercell) to actually print useful information?

### ISSUE THREAD

**Issue by jli5373** [prisms-center/CASMcode_configuration#13]
Currently, in python, if you run print(supercell) on some configuration.Supercell object, it just prints that there's a configuration.Supercell object at x memory address.

Can we define the __str__/__repr__ (python) or >> (c++) operator for these objects so that the output when you try to print them is  meaningful (ie. the supercell name)? I'm not sure how the conversion from the c++ backend to the python side works though.

If this could be implemented for all the different classes that frequently get looked at (ie. Configuration, SupercellSymOp, Prim, xtal.Structure, etc) it would be a major quality of life improvement when working with casm since I feel like there are quite a few annoying barriers to ease of use with the current casmv2.

**Comment by bpuchala** [comment]
1. Yes, I agree it would be nice to have `__str__` definition for most objects.
2. Currently, for a large majority of cases the following works :
  ```
  from libcasm.xtal import pretty_json
  print(pretty_json(obj.to_dict()))
  ```
  The `pretty_json` method is a bit easier to read than `json.dumps(obj, indent=2)` for many objects because it keeps innermost arrays on the same line.
3. For the most commonly used classes, would  `__str__` being equivalent to `pretty_json(obj.to_dict())` be good?

**Comment by jli5373** [comment]
I think making `__str__ ` equivalent to the `pretty_json(obj.to_dict())`  would be good. It probably solves most of the issues there.
